[[headers]]
  for = "/*.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.wasm.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.data.gz"
  [headers.values]
    Content-Encoding = "gzip"
    Content-Type = "application/octet-stream"
    Cache-Control = "public, max-age=31536000"
